"use client";
import { useState } from "react";
import { Figure, Switcher } from "@/components/three/Figure";
import { Stage } from "@/components/three/Stage";
import { Halo, Motes, Node3D, PointerTilt, Ribbon, Slab, Tag } from "@/components/three/atoms";
import { P } from "@/lib/palette";
import { useCopy } from "@/lib/useCopy";
type Mode="tiers"|"meter"|"cache";
const COPY={en:{label:"quotas make economics visible",hint:"tiers · token meter · cache discount",tiers:"tiers",meter:"token meter",cache:"cache discount",free:"free",pro:"pro",credits:"credits",tokens:"tokens/min",full:"full price",cached:"cached prefix"},es:{label:"las cuotas hacen visible la economía",hint:"niveles · medidor · descuento caché",tiers:"niveles",meter:"medidor",cache:"descuento caché",free:"free",pro:"pro",credits:"créditos",tokens:"tokens/min",full:"precio completo",cached:"prefijo en caché"}};
export default function Visual(){const t=useCopy(COPY);const [mode,setMode]=useState<Mode>("tiers");return <Figure label={t.label} hint={t.hint} legend={[{color:P.teal,label:t.free},{color:P.violet,label:t.pro},{color:P.amber,label:t.credits}]} controls={<Switcher value={mode} onChange={setMode} options={[{value:"tiers",label:t.tiers,tone:P.teal},{value:"meter",label:t.meter,tone:P.amber},{value:"cache",label:t.cache,tone:P.violet}]} ariaLabel={t.label}/>}> <Stage className="h-full w-full" camera={{position:[0,.3,8.6],fov:37}}><Motes count={100} radius={7} opacity={.3}/><PointerTilt amount={.07}>
{mode==="tiers"&&<>{[[t.free,P.teal,.8],[t.pro,P.violet,1.4],[t.credits,P.amber,2.2]].map(([lab,col,h],i)=><group key={lab as string}><Slab position={[-2+i*2,-.7+(h as number)/2,0]} size={[1.4,h as number,.14]} color={col as string} fill={.25}/><Tag position={[-2+i*2,1.55,.15]} tone={(["teal","violet","amber"] as const)[i]} size="xs">{lab as string}</Tag></group>)}</>}
{mode==="meter"&&<><Slab position={[0,.5,0]} size={[4,.65,.14]} color={P.muted} fill={.12}/><Slab position={[-.7,.5,.1]} size={[2.4,.65,.06]} color={P.amber} fill={.45}/><Tag position={[0,1.15,.15]} tone="amber">{t.tokens}</Tag><Node3D position={[1.25,.5,.2]} color={P.rose} radius={.12} pulse={.5}/><Tag position={[1.2,-.15,.15]} tone="rose" size="xs">limit</Tag></>}
{mode==="cache"&&<><Slab position={[-1.6,.5,0]} size={[2.1,.8,.14]} color={P.rose} fill={.25}/><Tag position={[-1.6,1.05,.15]} tone="rose">{t.full}</Tag><Ribbon points={[[-.4,.5,0],[.4,.5,0]]} color={P.teal} radius={.05} opacity={.85}/><Slab position={[1.6,.5,0]} size={[2.1,.8,.14]} color={P.teal} fill={.3}/><Halo position={[1.6,.5,0]} radius={.8} color={P.teal} opacity={.35} spin={.15}/><Tag position={[1.6,1.05,.15]} tone="teal">{t.cached}</Tag><Tag position={[0,-.5,.15]} tone="muted" size="xs">reuse prefix → menor coste</Tag></>}
</PointerTilt></Stage></Figure>}
