"use client";
import { useState } from "react";
import { Figure, Switcher } from "@/components/three/Figure";
import { Stage } from "@/components/three/Stage";
import { Motes, Node3D, PointerTilt, Ribbon, Slab, Tag } from "@/components/three/atoms";
import { P } from "@/lib/palette";
import { useCopy } from "@/lib/useCopy";
type Mode="local"|"router"|"endpoint";
const COPY={en:{label:"inference is a placement decision",hint:"local · router · endpoint",local:"local pipeline",router:"router",endpoint:"endpoint",cache:"cache",token:"HF_TOKEN",slug:"model slug",fastest:"fastest",dedicated:"dedicated gpu"},es:{label:"inferir es decidir dónde ejecutar",hint:"local · router · endpoint",local:"pipeline local",router:"router",endpoint:"endpoint",cache:"caché",token:"HF_TOKEN",slug:"slug del modelo",fastest:"fastest",dedicated:"gpu dedicada"}};
export default function Visual(){const t=useCopy(COPY);const [mode,setMode]=useState<Mode>("local");return <Figure label={t.label} hint={t.hint} legend={[{color:P.teal,label:t.local},{color:P.violet,label:t.router},{color:P.amber,label:t.endpoint}]} controls={<Switcher value={mode} onChange={setMode} options={[{value:"local",label:t.local,tone:P.teal},{value:"router",label:t.router,tone:P.violet},{value:"endpoint",label:t.endpoint,tone:P.amber}]} ariaLabel={t.label}/>}> <Stage className="h-full w-full" camera={{position:[0,.3,8.6],fov:37}}><Motes count={100} radius={7} opacity={.3}/><PointerTilt amount={.07}>
{mode==="local"&&<><Slab position={[-2,.5,0]} size={[1.6,.8,.12]} color={P.teal} fill={.22}/><Tag position={[-2,1.05,.15]} tone="teal">python pipeline</Tag><Ribbon points={[[-1.1,.5,0],[.2,.5,0]]} color={P.teal} radius={.05} opacity={.85}/><Slab position={[1.1,.5,0]} size={[1.7,.8,.12]} color={P.violet} fill={.2}/><Tag position={[1.1,1.05,.15]} tone="violet">{t.cache}</Tag><Tag position={[0,-.5,.15]} tone="muted" size="xs">weights → cache → tokens</Tag></>}
{mode==="router"&&<><Slab position={[-1.7,.5,0]} size={[1.7,.8,.12]} color={P.violet} fill={.22}/><Tag position={[-1.7,1.05,.15]} tone="violet">{t.token}</Tag><Ribbon points={[[-.7,.5,0],[.3,.5,0]]} color={P.amber} radius={.05} opacity={.85}/><Node3D position={[1.1,.5,0]} color={P.amber} radius={.22} pulse={.35}/><Tag position={[1.1,1.05,.15]} tone="amber">{t.router}</Tag><Tag position={[1.1,-.2,.15]} tone="muted" size="xs">{t.slug}:fastest</Tag></>}
{mode==="endpoint"&&<><Slab position={[-1.5,.5,0]} size={[1.7,1,.14]} color={P.violet} fill={.18}/><Tag position={[-1.5,1.15,.15]} tone="violet">serverless pool</Tag><Ribbon points={[[0,.5,0],[.8,.5,0]]} color={P.amber} radius={.05} opacity={.85}/><Slab position={[1.8,.5,0]} size={[1.8,1,.14]} color={P.amber} fill={.24}/><Tag position={[1.8,1.15,.15]} tone="amber">{t.dedicated}</Tag><Tag position={[0,-.55,.15]} tone="muted" size="xs">shared latency vs control</Tag></>}
</PointerTilt></Stage></Figure>}
