"use client";
import { useState } from "react";
import { Figure, Switcher } from "@/components/three/Figure";
import { Stage } from "@/components/three/Stage";
import { Halo, Motes, Node3D, PointerTilt, Ribbon, Slab, Tag } from "@/components/three/atoms";
import { P } from "@/lib/palette";
import { useCopy } from "@/lib/useCopy";
type Mode = "belt" | "loop" | "sandbox";
const COPY = { en: { label: "tools turn intent into side effects", hint: "toolbelt · loop · sandbox", belt: "toolbelt", loop: "loop", sandbox: "sandbox", search: "search", files: "files", terminal: "terminal", patch: "patch", call: "call", result: "result", deny: "deny", allow: "allow" }, es: { label: "las tools convierten intención en efectos", hint: "cinturón · bucle · sandbox", belt: "cinturón", loop: "bucle", sandbox: "sandbox", search: "busca", files: "ficheros", terminal: "terminal", patch: "patch", call: "llamada", result: "resultado", deny: "deniega", allow: "permite" } };
export default function Visual(){const t=useCopy(COPY);const [mode,setMode]=useState<Mode>("belt");return <Figure label={t.label} hint={t.hint} legend={[{color:P.teal,label:t.allow},{color:P.rose,label:t.deny},{color:P.violet,label:t.result}]} controls={<Switcher value={mode} onChange={setMode} options={[{value:"belt",label:t.belt,tone:P.teal},{value:"loop",label:t.loop,tone:P.violet},{value:"sandbox",label:t.sandbox,tone:P.rose}]} ariaLabel={t.label}/>}> <Stage className="h-full w-full" camera={{position:[0,.3,8.6],fov:37}}><Motes count={100} radius={7} opacity={.3}/><PointerTilt amount={.07}>
{mode==="belt"&&<>{[[t.search,P.teal,-2],[t.files,P.violet,0],[t.terminal,P.amber,2]].map(([lab,col,x],i)=><group key={lab as string}><Node3D position={[x as number,.6,0]} color={col as string} radius={.2} pulse={.2}/><Tag position={[x as number,1.1,.15]} tone={(["teal","violet","amber"] as const)[i]}>{lab as string}</Tag><Ribbon points={[[x as number,.2,0],[0,-.7,0]]} color={col as string} radius={.03} opacity={.7}/></group>)}<Slab position={[0,-1.1,0]} size={[2.2,.45,.1]} color={P.muted} fill={.15}/><Tag position={[0,-1.5,.15]} tone="muted" size="xs">agent chooses one</Tag></>}
{mode==="loop"&&<><Node3D position={[0,.7,0]} color={P.violet} radius={.22} pulse={.3}/><Tag position={[0,1.25,.15]} tone="violet">{t.call}</Tag><Ribbon points={[[0,.35,0],[0,-.25,0]]} color={P.teal} radius={.05} opacity={.85}/><Slab position={[0,-.7,0]} size={[1.8,.7,.12]} color={P.teal} fill={.25}/><Tag position={[0,-.2,.15]} tone="teal">{t.result}</Tag><Ribbon points={[[.8,-.7,0],[2,-.2,0],[2,.8,0],[.5,1.3,0]]} color={P.lineStrong} radius={.03} opacity={.7}/><Halo position={[0,.2,0]} radius={1.55} color={P.violet} opacity={.25} spin={.1}/></>}
{mode==="sandbox"&&<><Halo position={[0,.3,0]} radius={1.7} color={P.rose} opacity={.42} spin={.1}/><Slab position={[0,.3,0]} size={[2.7,1.8,.14]} color={P.teal} fill={.16} rim={.7}/><Tag position={[0,1.45,.15]} tone="teal">exec root</Tag><Node3D position={[0,.3,.2]} color={P.amber} radius={.2} pulse={.3}/><Tag position={[0,-.85,.15]} tone="rose" size="xs">{t.deny} fuera del root</Tag></>}
</PointerTilt></Stage></Figure>}
