import type { Locale } from "@/i18n/routing";

export type GlossaryTerm = {
  id: string;
  module: string;
  term: { en: string; es: string };
  def: { en: string; es: string };
};

export const GLOSSARY: GlossaryTerm[] = [
  { id: "model", module: "orientation", term: { en: "model", es: "modelo" }, def: { en: "A file of learned weights plus a recipe for scoring the next token. Not a hand-written program of rules.", es: "Un archivo de pesos aprendidos más una receta para puntuar el siguiente token. No es un programa de reglas escritas a mano." } },
  { id: "weights", module: "orientation", term: { en: "weights", es: "pesos" }, def: { en: "The numbers that are the model. They live on disk. Changing them is training or an adapter, not a longer prompt.", es: "Los números que son el modelo. Viven en disco. Cambiarlos es entrenar o poner un adapter, no alargar el prompt." } },
  { id: "parameter", module: "orientation", term: { en: "parameter", es: "parámetro" }, def: { en: "One learned number in the file. «7B» means about seven billion parameters: size, not a grade.", es: "Un número aprendido del archivo. «7B» son unos siete mil millones de parámetros: tamaño, no una nota." } },
  { id: "hallucination", module: "orientation", term: { en: "hallucination", es: "alucinación" }, def: { en: "Fluent next-token continuation that is not grounded in a retrieved fact. Confidence is not evidence.", es: "Una continuación fluida del siguiente token que no está anclada a un hecho pegado en el prompt. La seguridad no es prueba." } },
  { id: "token", module: "language-of-models", term: { en: "token", es: "token" }, def: { en: "A chunk of text the model reads and writes. Not always a word: hello may be one token; a rare name may be several.", es: "Un trozo de texto que el modelo lee y escribe. No siempre es una palabra." } },
  { id: "tokenizer", module: "language-of-models", term: { en: "tokenizer", es: "tokenizador" }, def: { en: "The piece that splits text into token ids. It is part of the model artifact: swap it and you have another model.", es: "La pieza que parte el texto en ids. Viaja con el modelo: cámbiala y tienes otro modelo." } },
  { id: "context-window", module: "language-of-models", term: { en: "context window", es: "ventana de contexto" }, def: { en: "The maximum number of tokens the model can attend over in one pass — prompt plus generation so far.", es: "El número máximo de tokens sobre los que el modelo puede atender en una pasada: prompt más lo generado." } },
  { id: "embedding", module: "language-of-models", term: { en: "embedding", es: "embedding" }, def: { en: "A list of numbers that places a token (or a passage) in a space where nearby points mean related things.", es: "Una lista de números que sitúa un token (o un pasaje) en un espacio donde los puntos cercanos significan cosas afines." } },
  { id: "next-token", module: "language-of-models", term: { en: "next-token prediction", es: "predicción del siguiente token" }, def: { en: "The core job: given tokens so far, score every token in the vocabulary as the next one.", es: "La tarea central: dados los tokens hasta ahora, puntuar cada token del vocabulario como el siguiente." } },
  { id: "logits", module: "language-of-models", term: { en: "logits", es: "logits" }, def: { en: "Raw scores for each vocabulary item, before they are turned into probabilities.", es: "Puntuaciones crudas para cada ítem del vocabulario, antes de convertirse en probabilidades." } },
  { id: "softmax", module: "maths-you-need", term: { en: "softmax", es: "softmax" }, def: { en: "Turns a vector of scores into a probability distribution that sums to 1.", es: "Convierte un vector de puntuaciones en una distribución de probabilidad que suma 1." } },
  { id: "sampling", module: "language-of-models", term: { en: "sampling", es: "muestreo" }, def: { en: "Drawing the next token from the probability distribution instead of always taking the top score.", es: "Elegir el siguiente token de la distribución en lugar de tomar siempre la puntuación más alta." } },
  { id: "temperature", module: "language-of-models", term: { en: "temperature", es: "temperatura" }, def: { en: "A knob that sharpens (low) or flattens (high) the next-token distribution. Zero is greedy.", es: "Un control que afila (baja) o aplana (alta) la distribución del siguiente token. Cero es greedy." } },
  { id: "top-p", module: "language-of-models", term: { en: "top-p (nucleus)", es: "top-p (núcleo)" }, def: { en: "Sample only from the smallest set of tokens whose probabilities sum to p.", es: "Muestrear solo del conjunto más pequeño de tokens cuyas probabilidades suman p." } },
  { id: "top-k", module: "language-of-models", term: { en: "top-k", es: "top-k" }, def: { en: "Sample only from the k highest-probability tokens.", es: "Muestrear solo de los k tokens con mayor probabilidad." } },
  { id: "prefill", module: "language-of-models", term: { en: "prefill", es: "prefill" }, def: { en: "The prompt-processing pass: prompt tokens are ingested, usually in parallel, and the KV cache is filled.", es: "La pasada que procesa el prompt: se ingieren los tokens, casi siempre en paralelo, y se llena la caché KV." } },
  { id: "decode", module: "language-of-models", term: { en: "decode", es: "decode" }, def: { en: "The generation pass: one new token at a time, reusing the KV cache.", es: "La pasada de generación: un token nuevo cada vez, reutilizando la caché KV." } },
  { id: "kv-cache", module: "language-of-models", term: { en: "KV cache", es: "caché KV" }, def: { en: "Stored key and value tensors from attention for tokens already seen, so decode does not recompute them.", es: "Tensores de keys y values de atención de tokens ya vistos, para no recomputarlos en el decode." } },
  { id: "greedy", module: "language-of-models", term: { en: "greedy decoding", es: "decodificación greedy" }, def: { en: "Always pick the highest-probability next token. Deterministic for a fixed prompt on a deterministic runtime.", es: "Elegir siempre el token de mayor probabilidad. Determinista con prompt y runtime fijos." } },
  { id: "harness", module: "the-harness", term: { en: "harness", es: "arnés" }, def: { en: "The loop around a model: system prompt, tools, threads, permissions, memory, and control flow. Not the model weights.", es: "El bucle alrededor de un modelo: system prompt, herramientas, hilos, permisos, memoria y control de flujo. No son los pesos." } },
  { id: "system-prompt", module: "the-harness", term: { en: "system prompt / profile", es: "system prompt / perfil" }, def: { en: "The standing instructions injected every turn (or cached) that shape role, style, and tool policy.", es: "Las instrucciones permanentes que se inyectan (o se cachean) y marcan rol, estilo y política de herramientas." } },
  { id: "tool", module: "the-harness", term: { en: "tool", es: "herramienta" }, def: { en: "A function the model can request: name, JSON schema, and an implementation the harness runs.", es: "Una función que el modelo puede pedir: nombre, esquema JSON e implementación que ejecuta el arnés." } },
  { id: "thread", module: "the-harness", term: { en: "thread", es: "hilo" }, def: { en: "A durable conversation: messages, tool results, and often a working directory or memory store.", es: "Una conversación durable: mensajes, resultados de herramientas y a menudo un directorio de trabajo o memoria." } },
  { id: "subagent", module: "the-harness", term: { en: "subagent", es: "subagente" }, def: { en: "A nested harness run with its own prompt, tools, and usually a smaller context, reporting back a summary.", es: "Una ejecución anidada del arnés con su propio prompt, herramientas y, casi siempre, un contexto más pequeño." } },
  { id: "permissions", module: "the-harness", term: { en: "permissions", es: "permisos" }, def: { en: "What the harness will actually execute: which tools, which paths, whether network is allowed.", es: "Lo que el arnés ejecutará de verdad: qué herramientas, qué rutas, si hay red." } },
  { id: "prompt-cache", module: "the-harness", term: { en: "prompt cache / prefix cache", es: "caché de prompt / prefijo" }, def: { en: "Reuse of computed prompt prefixes across requests. Not the same as the KV cache of one request.", es: "Reutilizar prefijos de prompt ya computados entre peticiones. No es la caché KV de una sola petición." } },
  { id: "compaction", module: "the-harness", term: { en: "compaction", es: "compactación" }, def: { en: "Summarising or dropping old thread turns so the next call fits in the context window.", es: "Resumir o tirar turnos viejos del hilo para que la siguiente llamada quepa en la ventana de contexto." } },
  { id: "kernel", module: "the-harness", term: { en: "kernel", es: "kernel" }, def: { en: "Two common meanings: a GPU kernel (the compiled GPU program) and a runtime kernel (the inner loop of a harness).", es: "Dos sentidos habituales: un kernel de GPU (el programa compilado) y el kernel de un runtime (el bucle interno del arnés)." } },
  { id: "nous-hermes", module: "the-harness", term: { en: "Nous Hermes", es: "Nous Hermes" }, def: { en: "A family of open-weight chat models from Nous Research. A model, not a harness. The harness is the loop you put around any model.", es: "Una familia de modelos chat de pesos abiertos de Nous Research. Es un modelo, no un arnés. El arnés es el bucle que pones alrededor de cualquier modelo." } },
  { id: "messages-api", module: "calls-cache-threads", term: { en: "messages API", es: "API de messages" }, def: { en: "Chat-style request: a list of role/content messages, often with tool calls in-band.", es: "Petición estilo chat: una lista de mensajes rol/contenido, a menudo con tool calls incluidos." } },
  { id: "completions-api", module: "calls-cache-threads", term: { en: "completions API", es: "API de completions" }, def: { en: "Raw prefix-completion: you send text, the model continues it. Still used under the hood and in some local servers.", es: "Completar un prefijo: envías texto y el modelo lo continúa. Sigue usándose por debajo y en algunos servidores locales." } },
  { id: "tool-call", module: "calls-cache-threads", term: { en: "tool_call", es: "tool_call" }, def: { en: "A structured request from the model to run a tool: id, name, arguments. The harness executes and returns a tool result message.", es: "Una petición estructurada del modelo para ejecutar una herramienta: id, nombre, argumentos." } },
  { id: "streaming", module: "calls-cache-threads", term: { en: "streaming", es: "streaming" }, def: { en: "Tokens (and sometimes tool-call fragments) arrive as they are generated, instead of waiting for the full response.", es: "Los tokens (y a veces fragmentos de tool_call) llegan mientras se generan." } },
  { id: "http-cache", module: "calls-cache-threads", term: { en: "HTTP cache", es: "caché HTTP" }, def: { en: "Ordinary web caching of GET responses. Almost never what people mean by the model cache.", es: "La caché web de respuestas GET. Casi nunca es lo que se quiere decir con la caché del modelo." } },
  { id: "turn", module: "calls-cache-threads", term: { en: "turn", es: "turno" }, def: { en: "One user message plus the model's work until it stops or returns control — may include several tool rounds.", es: "Un mensaje de usuario más el trabajo del modelo hasta que para — puede incluir varias rondas de herramientas." } },
  { id: "session", module: "calls-cache-threads", term: { en: "session", es: "sesión" }, def: { en: "A looser unit than a thread: often the lifetime of a tab, a login, or a process. Do not assume it maps 1:1 to context.", es: "Una unidad más laxa que un hilo: a menudo la vida de una pestaña o un proceso. No asumas que coincide con el contexto." } },
  { id: "closed-model", module: "model-zoo", term: { en: "closed model", es: "modelo cerrado" }, def: { en: "You call an API; you do not get the weights. The vendor chooses hardware, quant, and often the system prompt.", es: "Llamas a una API; no recibes los pesos. El proveedor elige hardware, cuantización y a menudo el system prompt." } },
  { id: "open-weights", module: "model-zoo", term: { en: "open weights", es: "pesos abiertos" }, def: { en: "The parameters are downloadable. The training data, code, and license may still be restricted.", es: "Los parámetros se pueden descargar. Los datos de entrenamiento, el código y la licencia pueden seguir restringidos." } },
  { id: "open-source-model", module: "model-zoo", term: { en: "open source (model)", es: "código abierto (modelo)" }, def: { en: "A stronger claim than open weights: look at the license, data, and training code. Many open models are open weights only.", es: "Una afirmación más fuerte que pesos abiertos: mira licencia, datos y código de entrenamiento." } },
  { id: "dense", module: "model-zoo", term: { en: "dense model", es: "modelo dense" }, def: { en: "Every parameter is used on every token. Contrast with Mixture of Experts.", es: "Cada parámetro se usa en cada token. Contrasta con Mixture of Experts." } },
  { id: "moe", module: "model-zoo", term: { en: "Mixture of Experts (MoE)", es: "Mixture of Experts (MoE)" }, def: { en: "A layer routes each token to a few expert MLPs. Total parameters can be huge; active parameters per token are smaller.", es: "Una capa enruta cada token a unos pocos expertos. Los parámetros totales pueden ser enormes; los activos por token son menos." } },
  { id: "base-model", module: "model-zoo", term: { en: "base model", es: "modelo base" }, def: { en: "Pretrained on next-token prediction, not tuned to follow instructions. Completes text; does not chat by default.", es: "Preentrenado para predecir el siguiente token, no ajustado a seguir instrucciones." } },
  { id: "instruct", module: "model-zoo", term: { en: "instruct / chat model", es: "modelo instruct / chat" }, def: { en: "A base model after SFT (and often preference training) so it follows a chat template.", es: "Un modelo base tras SFT (y a menudo preferencias) para seguir una plantilla de chat." } },
  { id: "reasoning-model", module: "model-zoo", term: { en: "reasoning model", es: "modelo de razonamiento" }, def: { en: "A variant trained or prompted to spend tokens on intermediate work before the answer. Costs more tokens; not magic.", es: "Una variante entrenada o inducida a gastar tokens en trabajo intermedio antes de la respuesta." } },
  { id: "model-card", module: "model-zoo", term: { en: "model card", es: "ficha del modelo" }, def: { en: "The Hugging Face (or vendor) page: license, architecture, context length, chat template, intended use, evals.", es: "La página en Hugging Face o del proveedor: licencia, arquitectura, contexto, plantilla de chat, uso previsto, evaluaciones." } },
  { id: "pretrain", module: "training", term: { en: "pretraining", es: "preentrenamiento" }, def: { en: "The expensive next-token run on a huge corpus that produces a base model. Not a laptop job.", es: "La pasada cara de siguiente-token sobre un corpus enorme que produce un modelo base. No es trabajo de portátil." } },
  { id: "sft", module: "training", term: { en: "SFT", es: "SFT" }, def: { en: "Supervised fine-tuning: train on prompt and desired completion pairs so the model imitates that style.", es: "Ajuste supervisado: entrenar con pares de prompt y continuación deseada para que el modelo imite ese estilo." } },
  { id: "rlhf", module: "training", term: { en: "RLHF", es: "RLHF" }, def: { en: "Reinforcement learning from human feedback: a reward model trained on human preferences, then a policy update (classically PPO).", es: "Aprendizaje por refuerzo con feedback humano: un modelo de recompensa con preferencias humanas y luego una actualización de política (clásicamente PPO)." } },
  { id: "dpo", module: "training", term: { en: "DPO", es: "DPO" }, def: { en: "Direct Preference Optimization: skip a separate reward model; use preference pairs to move the policy directly.", es: "Direct Preference Optimization: sin modelo de recompensa aparte; usa pares de preferencia para mover la política." } },
  { id: "rlaif", module: "training", term: { en: "RLAIF", es: "RLAIF" }, def: { en: "Like RLHF, but preference labels or critiques come from an AI judge rather than only humans.", es: "Como RLHF, pero las etiquetas de preferencia vienen de un juez de IA." } },
  { id: "ppo", module: "training", term: { en: "PPO", es: "PPO" }, def: { en: "Proximal Policy Optimization: an RL algorithm that updates the policy in small, clipped steps. Used in classic RLHF.", es: "Proximal Policy Optimization: un algoritmo de RL que actualiza la política a pasos recortados. Usado en el RLHF clásico." } },
  { id: "grpo", module: "training", term: { en: "GRPO", es: "GRPO" }, def: { en: "Group Relative Policy Optimization: a critic-light RL style used for reasoning and tool traces — sample a group of rollouts and learn from relative scores.", es: "Group Relative Policy Optimization: un estilo de RL sin crítico pesado, usado en trazas de razonamiento y herramientas." } },
  { id: "lora", module: "fine-tuning", term: { en: "LoRA", es: "LoRA" }, def: { en: "Low-Rank Adaptation: freeze the base weights; learn a pair of small matrices whose product is the update.", es: "Low-Rank Adaptation: congela los pesos base y aprende un par de matrices pequeñas cuyo producto es la actualización." } },
  { id: "qlora", module: "fine-tuning", term: { en: "QLoRA", es: "QLoRA" }, def: { en: "LoRA while the base model sits in 4-bit (typically NF4) in memory. Makes larger models fit on one GPU for training.", es: "LoRA con el modelo base en 4 bits (típicamente NF4) en memoria. Hace que modelos más grandes quepan en una GPU para entrenar." } },
  { id: "full-ft", module: "fine-tuning", term: { en: "full fine-tune", es: "ajuste completo" }, def: { en: "Update all or most parameters. Highest capacity, highest memory and overfit risk.", es: "Actualizar todos o casi todos los parámetros. Más capacidad, más memoria y más riesgo de sobreajuste." } },
  { id: "peft", module: "fine-tuning", term: { en: "PEFT", es: "PEFT" }, def: { en: "Parameter-efficient fine-tuning: the family that includes LoRA, adapters, prefix-tuning.", es: "Ajuste eficiente en parámetros: la familia que incluye LoRA, adapters, prefix-tuning." } },
  { id: "gguf", module: "local-inference", term: { en: "GGUF", es: "GGUF" }, def: { en: "The llama.cpp file format: weights, tokenizer, and metadata in one file. Usually already quantized.", es: "El formato de llama.cpp: pesos, tokenizador y metadatos en un archivo. Suele venir ya cuantizado." } },
  { id: "safetensors", module: "local-inference", term: { en: "safetensors", es: "safetensors" }, def: { en: "A safe tensor container used by Hugging Face and many GPU servers. Not itself a quant scheme.", es: "Un contenedor de tensores usado por Hugging Face y muchos servidores GPU. No es un esquema de cuantización." } },
  { id: "exl2", module: "local-inference", term: { en: "EXL2", es: "EXL2" }, def: { en: "ExLlamaV2 GPU-oriented quant format with a target bitrate. Not interchangeable with GGUF.", es: "Formato de cuantización de ExLlamaV2 orientado a GPU, con un bitrate objetivo. No es intercambiable con GGUF." } },
  { id: "llamacpp", module: "local-inference", term: { en: "llama.cpp", es: "llama.cpp" }, def: { en: "C/C++ runtime for GGUF models. CPU, Metal, CUDA, and more. The engine under Ollama and many desktop apps.", es: "Runtime C/C++ para modelos GGUF. CPU, Metal, CUDA y más. El motor bajo Ollama y muchas apps de escritorio." } },
  { id: "ollama", module: "local-inference", term: { en: "Ollama", es: "Ollama" }, def: { en: "A local server and CLI that pulls GGUF-style models and exposes an HTTP API. Convenient, fewer knobs.", es: "Un servidor local y CLI que baja modelos estilo GGUF y expone una API HTTP. Cómodo, menos palancas." } },
  { id: "vllm", module: "local-inference", term: { en: "vLLM", es: "vLLM" }, def: { en: "A GPU inference server built for throughput: paged KV cache, continuous batching. Typical for NVIDIA boxes serving many users.", es: "Servidor de inferencia GPU pensado para throughput: KV cache paginada, batching continuo." } },
  { id: "mlx", module: "local-inference", term: { en: "MLX", es: "MLX" }, def: { en: "Apple array framework. MLX-LM runs and can fine-tune models in unified memory on Apple Silicon.", es: "El framework de arrays de Apple. MLX-LM ejecuta y puede ajustar modelos en la memoria unificada de Apple Silicon." } },
  { id: "quantization", module: "quantization", term: { en: "quantization", es: "cuantización" }, def: { en: "Storing and often computing with weights in fewer bits. Shrinks memory; can nick quality.", es: "Guardar y a menudo computar pesos con menos bits. Reduce memoria; puede rozar la calidad." } },
  { id: "q4km", module: "quantization", term: { en: "Q4_K_M", es: "Q4_K_M" }, def: { en: "A llama.cpp K-quant: roughly 4-bit, mixed precision, medium quality profile. A common default GGUF.", es: "Un K-quant de llama.cpp: unos 4 bits, precisión mixta, perfil medio. Un GGUF por defecto muy habitual." } },
  { id: "gptq", module: "quantization", term: { en: "GPTQ", es: "GPTQ" }, def: { en: "A post-training GPU quant method, often 4-bit, that uses calibration data. Common in vLLM stacks.", es: "Un método de cuantización GPU post-entrenamiento, a menudo 4 bits, con datos de calibración." } },
  { id: "awq", module: "quantization", term: { en: "AWQ", es: "AWQ" }, def: { en: "Activation-aware Weight Quantization: protects salient weights using activation statistics. Also common on GPU servers.", es: "Activation-aware Weight Quantization: protege pesos sensibles usando estadísticas de activación." } },
  { id: "nf4", module: "quantization", term: { en: "NF4", es: "NF4" }, def: { en: "4-bit NormalFloat, used by QLoRA and bitsandbytes. A training-time data type, not a GGUF filename.", es: "4-bit NormalFloat, usado por QLoRA y bitsandbytes. Un tipo en entrenamiento, no un nombre de archivo GGUF." } },
  { id: "vram", module: "memory-hardware", term: { en: "VRAM", es: "VRAM" }, def: { en: "Memory on a discrete GPU. Fast for the GPU; size is the usual limit for weights plus KV cache.", es: "Memoria de una GPU discreta. Rápida para la GPU; su tamaño suele limitar pesos más caché KV." } },
  { id: "unified-memory", module: "memory-hardware", term: { en: "unified memory", es: "memoria unificada" }, def: { en: "On Apple Silicon, CPU and GPU share one pool. No PCIe copy of the whole model; bandwidth is still finite.", es: "En Apple Silicon, CPU y GPU comparten un pool. No hay copia PCIe del modelo entero; el ancho de banda sigue siendo finito." } },
  { id: "pcie", module: "memory-hardware", term: { en: "PCIe", es: "PCIe" }, def: { en: "The bus between CPU RAM and a discrete GPU. Moving tensors across it is slower than staying in VRAM.", es: "El bus entre la RAM y una GPU discreta. Mover tensores por él es más lento que quedarse en VRAM." } },
  { id: "bandwidth", module: "memory-hardware", term: { en: "memory bandwidth", es: "ancho de banda de memoria" }, def: { en: "How fast you can stream weights and KV. Decode is often bandwidth-bound, not FLOPs-bound.", es: "Qué tan rápido puedes leer pesos y KV. El decode suele estar limitado por ancho de banda, no por FLOPs." } },
  { id: "attention", module: "maths-you-need", term: { en: "attention", es: "atención" }, def: { en: "For each token, mix information from other tokens using learned queries, keys, and values.", es: "Para cada token, mezclar información de otros tokens usando queries, keys y values aprendidos." } },
  { id: "cross-entropy", module: "maths-you-need", term: { en: "cross-entropy", es: "entropía cruzada" }, def: { en: "The usual training loss for next-token prediction: how surprised the model was by the true next token.", es: "La pérdida habitual al predecir el siguiente token: cuánto sorprendió al modelo el token verdadero." } },
  { id: "gradient", module: "maths-you-need", term: { en: "gradient", es: "gradiente" }, def: { en: "The direction to nudge parameters to reduce loss. Backprop computes it; optimizers step along it.", es: "La dirección para mover parámetros y reducir la pérdida. El backprop lo calcula; el optimizador da el paso." } },
  { id: "rank", module: "maths-you-need", term: { en: "rank (LoRA)", es: "rango (LoRA)" }, def: { en: "The inner dimension of the LoRA pair. Small rank means few extra parameters; too small may underfit.", es: "La dimensión interna del par LoRA. Rango pequeño significa pocos parámetros extra; demasiado pequeño puede quedarse corto." } },
];

export function getTerm(id: string) {
  return GLOSSARY.find((t) => t.id === id);
}

export function localizeTerm(t: GlossaryTerm, locale: Locale) {
  return { id: t.id, module: t.module, term: t.term[locale], def: t.def[locale] };
}
