"use client";
import { useState } from "react";
import { Figure, Switcher } from "@/components/three/Figure";
import { Stage } from "@/components/three/Stage";
import { Motes, Node3D, PointerTilt, Ribbon, Slab, Tag } from "@/components/three/atoms";
import { P } from "@/lib/palette";
import { useCopy } from "@/lib/useCopy";
type Mode="surfaces"|"session"|"stream";
const COPY={en:{label:"a gateway turns surfaces into sessions",hint:"surfaces · session · stream",surfaces:"surfaces",session:"session",stream:"stream",web:"web",mobile:"mobile",telegram:"telegram",whatsapp:"whatsapp",id:"session id",chunks:"chunks"},es:{label:"un gateway convierte superficies en sesiones",hint:"superficies · sesión · stream",surfaces:"superficies",session:"sesión",stream:"stream",web:"web",mobile:"móvil",telegram:"telegram",whatsapp:"whatsapp",id:"id de sesión",chunks:"trozos"}};
export default function Visual(){const t=useCopy(COPY);const [mode,setMode]=useState<Mode>("surfaces");return <Figure label={t.label} hint={t.hint} legend={[{color:P.teal,label:t.web},{color:P.violet,label:t.session},{color:P.amber,label:t.stream}]} controls={<Switcher value={mode} onChange={setMode} options={[{value:"surfaces",label:t.surfaces,tone:P.teal},{value:"session",label:t.session,tone:P.violet},{value:"stream",label:t.stream,tone:P.amber}]} ariaLabel={t.label}/>}> <Stage className="h-full w-full" camera={{position:[0,.3,8.6],fov:37}}><Motes count={100} radius={7} opacity={.3}/><PointerTilt amount={.07}>
{mode==="surfaces"&&<>{[[t.web,P.teal,-2],[t.mobile,P.violet,-.7],[t.telegram,P.amber,.7],[t.whatsapp,P.rose,2]].map(([lab,col,x],i)=><group key={lab as string}><Node3D position={[x as number,1,0]} color={col as string} radius={.17} pulse={.2}/><Tag position={[x as number,1.45,.15]} tone={(["teal","violet","amber","rose"] as const)[i]} size="xs">{lab as string}</Tag><Ribbon points={[[x as number,.7,0],[0,.1,0]]} color={col as string} radius={.03} opacity={.7}/></group>)}<Slab position={[0,-.5,0]} size={[2.2,.8,.14]} color={P.teal} fill={.25} rim={.7}/><Tag position={[0,-1.05,.15]} tone="teal">gateway</Tag></>}
{mode==="session"&&<><Slab position={[-2,.5,0]} size={[1.8,.8,.12]} color={P.teal} fill={.22}/><Tag position={[-2,1.05,.15]} tone="teal">message</Tag><Ribbon points={[[-1,.5,0],[.3,.5,0]]} color={P.violet} radius={.05} opacity={.85}/><Node3D position={[1.1,.5,0]} color={P.violet} radius={.23} pulse={.35}/><Tag position={[1.1,1.05,.15]} tone="violet">{t.id}</Tag><Ribbon points={[[1.35,.5,0],[2.5,.5,0]]} color={P.lineStrong} radius={.04} opacity={.8}/></>}
{mode==="stream"&&<><Slab position={[-2,.5,0]} size={[1.5,.8,.12]} color={P.violet} fill={.22}/><Tag position={[-2,1.05,.15]} tone="violet">gateway</Tag>{[0,1,2,3].map(i=><Ribbon key={i} points={[[-1.2,.8-i*.2,0],[2.2,.8-i*.2,0]]} color={P.amber} radius={.035} opacity={.8}/>) }<Slab position={[2.5,.5,0]} size={[1.2,.8,.12]} color={P.teal} fill={.22}/><Tag position={[2.5,1.05,.15]} tone="teal">surface</Tag><Tag position={[.5,-.6,.15]} tone="amber" size="xs">SSE · {t.chunks}</Tag></>}
</PointerTilt></Stage></Figure>}
