"use client";
import { useState } from "react";
import { Figure, Switcher } from "@/components/three/Figure";
import { Stage } from "@/components/three/Stage";
import { Halo, Motes, Node3D, PointerTilt, Ribbon, Slab, Tag } from "@/components/three/atoms";
import { P } from "@/lib/palette";
import { useCopy } from "@/lib/useCopy";
type Mode="lifecycle"|"agentic"|"abort";
const COPY={en:{label:"the loop owns a whole lifecycle",hint:"receive · act · stream · persist",lifecycle:"lifecycle",agentic:"agentic",abort:"abort",receive:"receive",act:"act",stream:"stream",persist:"persist",tool:"tool call",stop:"stop signal"},es:{label:"el bucle posee todo el ciclo de vida",hint:"recibe · actúa · emite · persiste",lifecycle:"ciclo",agentic:"agentic",abort:"aborta",receive:"recibe",act:"actúa",stream:"emite",persist:"persiste",tool:"llamada tool",stop:"señal stop"}};
export default function Visual(){const t=useCopy(COPY);const [mode,setMode]=useState<Mode>("lifecycle");return <Figure label={t.label} hint={t.hint} legend={[{color:P.teal,label:t.receive},{color:P.violet,label:t.act},{color:P.amber,label:t.persist}]} controls={<Switcher value={mode} onChange={setMode} options={[{value:"lifecycle",label:t.lifecycle,tone:P.teal},{value:"agentic",label:t.agentic,tone:P.violet},{value:"abort",label:t.abort,tone:P.rose}]} ariaLabel={t.label}/>}> <Stage className="h-full w-full" camera={{position:[0,.3,8.6],fov:37}}><Motes count={100} radius={7} opacity={.3}/><PointerTilt amount={.07}>
{mode==="lifecycle"&&<>{[[t.receive,P.teal,-2],[t.act,P.violet,-.7],[t.stream,P.amber,.7],[t.persist,P.rose,2]].map(([lab,col,x],i)=><group key={lab as string}><Slab position={[x as number,.5,0]} size={[1.25,.8,.12]} color={col as string} fill={.24}/><Tag position={[x as number,1.05,.15]} tone={(["teal","violet","amber","rose"] as const)[i]} size="xs">{lab as string}</Tag>{i<3&&<Ribbon points={[[x as number+.65,.5,0],[(x as number)+.75,.5,0]]} color={P.lineStrong} radius={.035} opacity={.7}/>}</group>)}</>}
{mode==="agentic"&&<><Halo position={[0,.5,0]} radius={1.35} color={P.violet} opacity={.3} spin={.1}/><Node3D position={[0,.5,0]} color={P.violet} radius={.22} pulse={.3}/><Tag position={[0,1.05,.15]} tone="violet">while</Tag><Ribbon points={[[0,-.1,0],[-1.7,-.7,0]]} color={P.teal} radius={.04} opacity={.85}/><Slab position={[-2,-.85,0]} size={[1.3,.55,.1]} color={P.teal} fill={.24}/><Tag position={[-2,-.45,.15]} tone="teal" size="xs">{t.tool}</Tag><Ribbon points={[[0,.1,0],[1.8,-.7,0],[1.8,1.2,0],[.3,1.5,0]]} color={P.lineStrong} radius={.03} opacity={.7}/></>}
{mode==="abort"&&<><Node3D position={[0,.5,0]} color={P.amber} radius={.22} pulse={.3}/><Halo position={[0,.5,0]} radius={.7} color={P.amber} opacity={.55} spin={.2}/><Tag position={[0,1.05,.15]} tone="amber">final answer</Tag><Ribbon points={[[-2,.4,0],[2,1.0,0]]} color={P.rose} radius={.06} opacity={.95}/><Tag position={[2,1.35,.15]} tone="rose">{t.stop}</Tag></>}
</PointerTilt></Stage></Figure>}
