"use client";
import { useState } from "react";
import { Figure, Switcher } from "@/components/three/Figure";
import { Stage } from "@/components/three/Stage";
import { Halo, Motes, Node3D, PointerTilt, Ribbon, Slab, Tag } from "@/components/three/atoms";
import { P } from "@/lib/palette";
import { useCopy } from "@/lib/useCopy";
type Mode="registry"|"execution"|"errors";
const COPY={en:{label:"a tool is a typed side effect",hint:"registry · execution · errors",registry:"registry",execution:"execution",errors:"errors",definition:"definition",call:"call",result:"result",timeout:"timeout",retry:"retry"},es:{label:"una tool es un efecto lateral tipado",hint:"registro · ejecución · errores",registry:"registro",execution:"ejecución",errors:"errores",definition:"definición",call:"llamada",result:"resultado",timeout:"timeout",retry:"reintenta"}};
export default function Visual(){const t=useCopy(COPY);const [mode,setMode]=useState<Mode>("registry");return <Figure label={t.label} hint={t.hint} legend={[{color:P.teal,label:t.definition},{color:P.violet,label:t.result},{color:P.rose,label:t.errors}]} controls={<Switcher value={mode} onChange={setMode} options={[{value:"registry",label:t.registry,tone:P.teal},{value:"execution",label:t.execution,tone:P.violet},{value:"errors",label:t.errors,tone:P.rose}]} ariaLabel={t.label}/>}> <Stage className="h-full w-full" camera={{position:[0,.3,8.6],fov:37}}><Motes count={100} radius={7} opacity={.3}/><PointerTilt amount={.07}>
{mode==="registry"&&<><Slab position={[-1.7,.5,0]} size={[1.8,1.1,.14]} color={P.teal} fill={.22}/><Tag position={[-1.7,1.2,.15]} tone="teal">{t.definition}</Tag>{[[-1.7,.3],[ -1.7,.0]].map(([x,y],i)=><Tag key={i} position={[x,y,.15]} tone="muted" size="xs">{i===0?"name + schema":"handler"}</Tag>)}<Ribbon points={[[-.7,.5,0],[.5,.5,0]]} color={P.lineStrong} radius={.04} opacity={.8}/><Node3D position={[1.5,.5,0]} color={P.violet} radius={.2} pulse={.3}/><Tag position={[1.5,1.05,.15]} tone="violet">agent</Tag></>}
{mode==="execution"&&<><Slab position={[-1.8,.5,0]} size={[1.4,.7,.12]} color={P.teal} fill={.24}/><Tag position={[-1.8,1.0,.15]} tone="teal">{t.call}</Tag><Ribbon points={[[-1,.5,0],[.5,.5,0]]} color={P.violet} radius={.05} opacity={.85}/><Slab position={[1.5,.5,0]} size={[1.5,.7,.12]} color={P.violet} fill={.24}/><Tag position={[1.5,1.0,.15]} tone="violet">{t.result}</Tag><Ribbon points={[[1.5,-.1,0],[1.5,-.8,0],[-1.8,-.8,0],[-1.8,-.1,0]]} color={P.lineStrong} radius={.03} opacity={.65}/></>}
{mode==="errors"&&<><Slab position={[-1.7,.5,0]} size={[1.6,.7,.12]} color={P.teal} fill={.2}/><Tag position={[-1.7,1.0,.15]} tone="teal">{t.call}</Tag><Ribbon points={[[-.8,.5,0],[.5,.5,0]]} color={P.rose} radius={.05} opacity={.9}/><Node3D position={[1.4,.5,0]} color={P.rose} radius={.22} pulse={.5}/><Tag position={[1.4,1.0,.15]} tone="rose">{t.timeout}</Tag><Ribbon points={[[1.4,-.1,0],[-.2,-.9,0]]} color={P.amber} radius={.04} opacity={.8}/><Tag position={[0,-1.2,.15]} tone="amber" size="xs">{t.retry}</Tag></>}
</PointerTilt></Stage></Figure>}
