"use client";
import { useState } from "react";
import { Figure, Switcher } from "@/components/three/Figure";
import { Stage } from "@/components/three/Stage";
import { Halo, Motes, Node3D, PointerTilt, Ribbon, Slab, Tag } from "@/components/three/atoms";
import { P } from "@/lib/palette";
import { useCopy } from "@/lib/useCopy";
type Mode="perceive"|"actions"|"sandbox";
const COPY={en:{label:"browser use is perceive → act",hint:"perceive · actions · sandbox",perceive:"perceive",actions:"actions",sandbox:"sandbox",screenshot:"screenshot",model:"model",click:"click",type:"type",scroll:"scroll",isolated:"isolated"},es:{label:"usar navegador es percibir → actuar",hint:"percibe · acciones · sandbox",perceive:"percibe",actions:"acciones",sandbox:"sandbox",screenshot:"captura",model:"modelo",click:"click",type:"escribe",scroll:"scroll",isolated:"aislado"}};
export default function Visual(){const t=useCopy(COPY);const [mode,setMode]=useState<Mode>("perceive");return <Figure label={t.label} hint={t.hint} legend={[{color:P.teal,label:t.perceive},{color:P.violet,label:t.actions},{color:P.rose,label:t.sandbox}]} controls={<Switcher value={mode} onChange={setMode} options={[{value:"perceive",label:t.perceive,tone:P.teal},{value:"actions",label:t.actions,tone:P.violet},{value:"sandbox",label:t.sandbox,tone:P.rose}]} ariaLabel={t.label}/>}> <Stage className="h-full w-full" camera={{position:[0,.3,8.6],fov:37}}><Motes count={100} radius={7} opacity={.3}/><PointerTilt amount={.07}>
{mode==="perceive"&&<><Slab position={[-1.8,.5,0]} size={[2.2,1.3,.14]} color={P.teal} fill={.2}/><Tag position={[-1.8,1.35,.15]} tone="teal">{t.screenshot}</Tag><Ribbon points={[[-.7,.5,0],[.3,.5,0]]} color={P.teal} radius={.05} opacity={.85}/><Node3D position={[1.2,.5,0]} color={P.violet} radius={.22} pulse={.35}/><Tag position={[1.2,1.05,.15]} tone="violet">{t.model}</Tag></>}
{mode==="actions"&&<><Slab position={[0,-.5,0]} size={[3.5,.7,.14]} color={P.muted} fill={.15}/><Tag position={[0,-1,.15]} tone="muted">page</Tag>{[[t.click,P.teal,-1.8],[t.type,P.violet,0],[t.scroll,P.amber,1.8]].map(([lab,col,x],i)=><group key={lab as string}><Node3D position={[x as number,1,0]} color={col as string} radius={.17} pulse={.3}/><Tag position={[x as number,1.45,.15]} tone={(["teal","violet","amber"] as const)[i]} size="xs">{lab as string}</Tag><Ribbon points={[[x as number,.7,0],[x as number,-.1,0]]} color={col as string} radius={.03} opacity={.75}/></group>)}</>}
{mode==="sandbox"&&<><Halo position={[0,.4,0]} radius={1.8} color={P.rose} opacity={.42} spin={.1}/><Slab position={[0,.4,0]} size={[2.8,1.7,.14]} color={P.teal} fill={.16} rim={.7}/><Tag position={[0,1.45,.15]} tone="teal">{t.isolated}</Tag><Node3D position={[0,.4,.2]} color={P.amber} radius={.2} pulse={.3}/><Tag position={[0,-.75,.15]} tone="rose" size="xs">host fuera del halo: deny</Tag></>}
</PointerTilt></Stage></Figure>}
