"use client";
import { useState } from "react";
import { Figure, Switcher } from "@/components/three/Figure";
import { Stage } from "@/components/three/Stage";
import { Motes, Node3D, PointerTilt, Ribbon, Slab, Tag } from "@/components/three/atoms";
import { P } from "@/lib/palette";
import { useCopy } from "@/lib/useCopy";
type Mode="tracks"|"choose"|"tiers";
const COPY={en:{label:"the map is a set of decisions",hint:"tracks · choose · tiers",tracks:"tracks",choose:"choose",tiers:"hardware tiers",foundations:"foundations",harness:"harness",training:"training",metal:"metal",local:"local",cloud:"cloud",vendor:"vendor",m5:"M5 32GB",a100:"A100",h100:"H100"},es:{label:"el mapa es un conjunto de decisiones",hint:"vías · elige · niveles",tracks:"vías",choose:"elige",tiers:"niveles hardware",foundations:"fundamentos",harness:"arnés",training:"entrenamiento",metal:"metal",local:"local",cloud:"nube",vendor:"proveedor",m5:"M5 32GB",a100:"A100",h100:"H100"}};
export default function Visual(){const t=useCopy(COPY);const [mode,setMode]=useState<Mode>("tracks");return <Figure label={t.label} hint={t.hint} legend={[{color:P.teal,label:t.foundations},{color:P.violet,label:t.harness},{color:P.amber,label:t.metal}]} controls={<Switcher value={mode} onChange={setMode} options={[{value:"tracks",label:t.tracks,tone:P.teal},{value:"choose",label:t.choose,tone:P.violet},{value:"tiers",label:t.tiers,tone:P.amber}]} ariaLabel={t.label}/>}> <Stage className="h-full w-full" camera={{position:[0,.3,8.6],fov:37}}><Motes count={100} radius={7} opacity={.3}/><PointerTilt amount={.07}>
{mode==="tracks"&&<>{[[t.foundations,P.teal,-2.3],[t.harness,P.violet,-.8],[t.training,P.amber,.8],[t.metal,P.rose,2.3]].map(([lab,col,x],i)=><group key={lab as string}><Ribbon points={[[x as number,-1,0],[x as number,1.2,0]]} color={col as string} radius={.07} opacity={.75}/><Tag position={[x as number,1.55,.15]} tone={(["teal","violet","amber","rose"] as const)[i]} size="xs">{lab as string}</Tag></group>)}<Slab position={[0,-1.3,0]} size={[2.4,.45,.1]} color={P.violet} fill={.25}/><Tag position={[0,-1.7,.15]} tone="violet" size="xs">producto útil</Tag></>}
{mode==="choose"&&<><Node3D position={[0,1,0]} color={P.violet} radius={.22} pulse={.3}/><Tag position={[0,1.5,.15]} tone="violet">budget</Tag>{[[t.local,P.teal,-1.8],[t.cloud,P.amber,0],[t.vendor,P.rose,1.8]].map(([lab,col,x])=><group key={lab as string}><Ribbon points={[[0,.7,0],[x as number,.1,0]]} color={col as string} radius={.04} opacity={.8}/><Slab position={[x as number,-.6,0]} size={[1.4,.8,.12]} color={col as string} fill={.23}/><Tag position={[x as number,-.05,.15]} tone={col===P.teal?"teal":col===P.amber?"amber":"rose"} size="xs">{lab as string}</Tag></group>)}</>}
{mode==="tiers"&&<>{[[t.m5,P.teal,1], [t.a100,P.violet,1.8],[t.h100,P.amber,2.8]].map(([lab,col,h],i)=><group key={lab as string}><Slab position={[-1.8+i*1.8,-.6+(h as number)/2,0]} size={[1.2,h as number,.14]} color={col as string} fill={.25}/><Tag position={[-1.8+i*1.8,1.65,.15]} tone={(["teal","violet","amber"] as const)[i]} size="xs">{lab as string}</Tag></group>)}<Tag position={[0,-1.15,.15]} tone="muted" size="xs">memoria · coste · throughput</Tag></>}
</PointerTilt></Stage></Figure>}
