"use client";
import { useState } from "react";
import { Figure, Switcher } from "@/components/three/Figure";
import { Stage } from "@/components/three/Stage";
import { Halo, Motes, Node3D, PointerTilt, Ribbon, Slab, Tag } from "@/components/three/atoms";
import { P } from "@/lib/palette";
import { useCopy } from "@/lib/useCopy";
type Mode="compact"|"drop"|"safeguard";
const COPY={en:{label:"compression is a deliberate loss",hint:"compact · drop tools · safeguard",compact:"compact",drop:"drop tools",safeguard:"safeguard",thread:"thread",summary:"summary",tool:"tool result",keep:"keep",dropLabel:"drop",audit:"audit"},es:{label:"comprimir es perder con intención",hint:"compacta · quita tools · salvaguarda",compact:"compacta",drop:"quita tools",safeguard:"salvaguarda",thread:"hilo",summary:"resumen",tool:"resultado tool",keep:"conserva",dropLabel:"quita",audit:"audita"}};
export default function Visual(){const t=useCopy(COPY);const [mode,setMode]=useState<Mode>("compact");return <Figure label={t.label} hint={t.hint} legend={[{color:P.teal,label:t.keep},{color:P.violet,label:t.summary},{color:P.rose,label:t.dropLabel}]} controls={<Switcher value={mode} onChange={setMode} options={[{value:"compact",label:t.compact,tone:P.teal},{value:"drop",label:t.drop,tone:P.rose},{value:"safeguard",label:t.safeguard,tone:P.amber}]} ariaLabel={t.label}/>}> <Stage className="h-full w-full" camera={{position:[0,.3,8.6],fov:37}}><Motes count={100} radius={7} opacity={.3}/><PointerTilt amount={.07}>
{mode==="compact"&&<><>{[0,1,2,3,4].map(i=><Slab key={i} position={[-2+i*.8,.7-(i%2)*.3,0]} size={[.7,.5,.1]} color={P.teal} fill={.18}/>)}</><Ribbon points={[[-.3,.5,0],[.6,-.1,0]]} color={P.violet} radius={.05} opacity={.8}/><Slab position={[1.5,-.4,0]} size={[1.6,.8,.14]} color={P.violet} fill={.28}/><Tag position={[1.5,.15,.15]} tone="violet">{t.summary}</Tag><Tag position={[0,-1.1,.15]} tone="muted" size="xs">10k → 200 tokens</Tag></>}
{mode==="drop"&&<>{[[t.keep,P.teal,-1.7],[t.tool,P.rose,0],[t.summary,P.violet,1.7]].map(([lab,col,x],i)=><group key={lab as string}><Slab position={[x as number,.5,0]} size={[1.4,.8,.12]} color={col as string} fill={i===1?.3:.22}/><Tag position={[x as number,1.05,.15]} tone={i===0?"teal":i===1?"rose":"violet"} size="xs">{lab as string}</Tag></group>)}<Ribbon points={[[0,.1,0],[0,-.8,0]]} color={P.rose} radius={.05} opacity={.85}/><Tag position={[0,-1.2,.15]} tone="rose" size="xs">tool result → {t.dropLabel}</Tag></>}
{mode==="safeguard"&&<><Halo position={[0,.4,0]} radius={1.4} color={P.amber} opacity={.45} spin={.12}/><Node3D position={[0,.4,0]} color={P.amber} radius={.2} pulse={.3}/><Tag position={[0,1.0,.15]} tone="amber">{t.audit}</Tag><Slab position={[-2,.4,0]} size={[1.5,.7,.12]} color={P.teal} fill={.24}/><Tag position={[-2,.9,.15]} tone="teal">{t.thread}</Tag><Slab position={[2,.4,0]} size={[1.5,.7,.12]} color={P.rose} fill={.22}/><Tag position={[2,.9,.15]} tone="rose">unsafe input</Tag></>}
</PointerTilt></Stage></Figure>}
