"use client";
import { useState } from "react";
import { Figure, Switcher } from "@/components/three/Figure";
import { Stage } from "@/components/three/Stage";
import { Motes, Node3D, PointerTilt, Ribbon, Slab, Tag } from "@/components/three/atoms";
import { P } from "@/lib/palette";
import { useCopy } from "@/lib/useCopy";
type Mode="repo"|"revision"|"widget";
const COPY={en:{label:"a model repo is more than weights",hint:"anatomy · revision · widget",repo:"repo",revision:"revision",widget:"widget",card:"model card",weights:"weights",tokenizer:"tokenizer",config:"config",main:"main",pr:"pull request",tokens:"tokens"},es:{label:"un repo de modelo es más que pesos",hint:"anatomía · revisión · widget",repo:"repo",revision:"revisión",widget:"widget",card:"model card",weights:"pesos",tokenizer:"tokenizador",config:"config",main:"main",pr:"pull request",tokens:"tokens"}};
export default function Visual(){const t=useCopy(COPY);const [mode,setMode]=useState<Mode>("repo");return <Figure label={t.label} hint={t.hint} legend={[{color:P.teal,label:t.card},{color:P.violet,label:t.weights},{color:P.amber,label:t.config}]} controls={<Switcher value={mode} onChange={setMode} options={[{value:"repo",label:t.repo,tone:P.teal},{value:"revision",label:t.revision,tone:P.violet},{value:"widget",label:t.widget,tone:P.amber}]} ariaLabel={t.label}/>}> <Stage className="h-full w-full" camera={{position:[0,.3,8.6],fov:37}}><Motes count={100} radius={7} opacity={.3}/><PointerTilt amount={.07}>
{mode==="repo"&&<>{[[t.card,P.teal,-2],[t.weights,P.violet,0],[t.tokenizer,P.amber,2],[t.config,P.rose,0]].map(([lab,col,x],i)=><group key={lab as string}><Slab position={[x as number,.85-(i===3?1.3:0),0]} size={[1.5,.7,.12]} color={col as string} fill={.22}/><Tag position={[x as number,1.35-(i===3?1.3:0),.15]} tone={(["teal","violet","amber","rose"] as const)[i]} size="xs">{lab as string}</Tag></group>)}</>}
{mode==="revision"&&<><Slab position={[0,.5,0]} size={[2.4,.8,.14]} color={P.teal} fill={.24}/><Tag position={[0,1.05,.15]} tone="teal">{t.main}</Tag><Ribbon points={[[0,.05,0],[-1.5,-.8,0]]} color={P.violet} radius={.04} opacity={.8}/><Slab position={[-1.8,-1.0,0]} size={[1.3,.55,.1]} color={P.violet} fill={.25}/><Tag position={[-1.8,-.55,.15]} tone="violet" size="xs">v1.1</Tag><Ribbon points={[[0,.05,0],[1.5,-.8,0]]} color={P.amber} radius={.04} opacity={.8}/><Slab position={[1.8,-1.0,0]} size={[1.3,.55,.1]} color={P.amber} fill={.25}/><Tag position={[1.8,-.55,.15]} tone="amber" size="xs">{t.pr}</Tag></>}
{mode==="widget"&&<><Slab position={[-1.7,.5,0]} size={[2.2,1.3,.14]} color={P.teal} fill={.18}/><Tag position={[-1.7,1.35,.15]} tone="teal">input box</Tag><Ribbon points={[[-.5,.5,0],[.5,.5,0]]} color={P.amber} radius={.05} opacity={.85}/>{[0,1,2,3].map(i=><Node3D key={i} position={[1.1+i*.35,.5,0]} color={P.amber} radius={.09} pulse={i*.2}/>)}<Tag position={[1.8,1.05,.15]} tone="amber" size="xs">{t.tokens}</Tag></>}
</PointerTilt></Stage></Figure>}
