"use client";
import { useState } from "react";
import { Figure, Switcher } from "@/components/three/Figure";
import { Stage } from "@/components/three/Stage";
import { Halo, Lattice, Motes, Node3D, PointerTilt, Ribbon, Slab, Tag } from "@/components/three/atoms";
import { P } from "@/lib/palette";
import { useCopy } from "@/lib/useCopy";
type Mode="routing"|"preset"|"structured";
const COPY={en:{label:"a preset is a contract with a provider",hint:"routing · anatomy · structured output",routing:"routing",preset:"preset",structured:"structured",provider:"provider",fallback:"fallback",model:"model",variant:"variant",schema:"schema",json:"JSON"},es:{label:"un preset es un contrato con un proveedor",hint:"routing · anatomía · salida estructurada",routing:"routing",preset:"preset",structured:"estructurada",provider:"proveedor",fallback:"fallback",model:"modelo",variant:"variante",schema:"esquema",json:"JSON"}};
export default function Visual(){const t=useCopy(COPY);const [mode,setMode]=useState<Mode>("routing");return <Figure label={t.label} hint={t.hint} legend={[{color:P.teal,label:t.provider},{color:P.violet,label:t.model},{color:P.amber,label:t.variant}]} controls={<Switcher value={mode} onChange={setMode} options={[{value:"routing",label:t.routing,tone:P.teal},{value:"preset",label:t.preset,tone:P.violet},{value:"structured",label:t.structured,tone:P.amber}]} ariaLabel={t.label}/>}> <Stage className="h-full w-full" camera={{position:[0,.3,8.6],fov:37}}><Motes count={100} radius={7} opacity={.3}/><PointerTilt amount={.07}>
{mode==="routing"&&<>{[[t.provider,P.teal,-2],[t.model,P.violet,0],[t.fallback,P.rose,2]].map(([lab,col,x],i)=><group key={lab as string}><Slab position={[x as number,.5,0]} size={[1.5,.8,.12]} color={col as string} fill={.22}/><Tag position={[x as number,1.05,.15]} tone={(["teal","violet","rose"] as const)[i]} size="xs">{lab as string}</Tag>{i<2&&<Ribbon points={[[ (x as number) + 0.75, 0.5, 0], [(x as number) + 1.0, 0.5, 0]]} color={col as string} radius={.035} opacity={.75}/>}</group>)}</>}
{mode==="preset"&&<><Slab position={[0,.4,0]} size={[4.4,1.6,.14]} color={P.violet} fill={.12} rim={.7}/>{[[t.provider,P.teal,-1.4,.7],[t.model,P.violet,0,.25],[t.variant,P.amber,1.4,-.2]].map(([lab,col,x,y])=><group key={lab as string}><Slab position={[x as number,y as number,.1]} size={[1.2,.35,.06]} color={col as string} fill={.3}/><Tag position={[x as number,(y as number)+.28,.18]} tone={col===P.teal?"teal":col===P.violet?"violet":"amber"} size="xs">{lab as string}</Tag></group>)}<Tag position={[0,-1.0,.15]} tone="muted" size="xs">preset = provider + model + variant</Tag></>}
{mode==="structured"&&<><Slab position={[-1.5,.5,0]} size={[2,.9,.14]} color={P.teal} fill={.2}/><Tag position={[-1.5,1.1,.15]} tone="teal">prompt</Tag><Ribbon points={[[-.4,.5,0],[.5,.5,0]]} color={P.amber} radius={.05} opacity={.85}/><Slab position={[1.5,.5,0]} size={[2,.9,.14]} color={P.amber} fill={.26}/><Tag position={[1.5,1.1,.15]} tone="amber">{t.schema}</Tag><Node3D position={[0,-.75,0]} color={P.violet} radius={.2} pulse={.3}/><Tag position={[0,-1.25,.15]} tone="violet" size="xs">{t.json} válido</Tag></>}
</PointerTilt></Stage></Figure>}
