"use client";
import { useState } from "react";
import { Figure, Switcher } from "@/components/three/Figure";
import { Stage } from "@/components/three/Stage";
import { Halo, Motes, Node3D, PointerTilt, Ribbon, Slab, Tag } from "@/components/three/atoms";
import { P } from "@/lib/palette";
import { useCopy } from "@/lib/useCopy";
type Mode = "resolver" | "fallback" | "modes";
const COPY = { en: { label: "a model string is a routing decision", hint: "resolver · fallback · modes", resolver: "resolver", fallback: "fallback", modes: "modes", model: "model", provider: "provider", url: "url", primary: "primary", backup: "backup", api: "api", chat: "chat", completions: "completions" }, es: { label: "un modelo es una decisión de routing", hint: "resolver · fallback · modos", resolver: "resuelve", fallback: "fallback", modes: "modos", model: "modelo", provider: "proveedor", url: "url", primary: "primario", backup: "reserva", api: "api", chat: "chat", completions: "completions" } };
export default function Visual() { const t = useCopy(COPY); const [mode,setMode]=useState<Mode>("resolver"); return <Figure label={t.label} hint={t.hint} legend={[{color:P.teal,label:t.model},{color:P.violet,label:t.provider},{color:P.amber,label:t.url}]} controls={<Switcher value={mode} onChange={setMode} options={[{value:"resolver",label:t.resolver,tone:P.teal},{value:"fallback",label:t.fallback,tone:P.rose},{value:"modes",label:t.modes,tone:P.amber}]} ariaLabel={t.label}/>}> <Stage className="h-full w-full" camera={{position:[0,.3,8.6],fov:37}}><Motes count={100} radius={7} opacity={.3}/><PointerTilt amount={.07}>
{mode==="resolver"&&<>{[[t.model,P.teal,-2],[t.provider,P.violet,0],[t.url,P.amber,2]].map(([lab,col,x],i)=><group key={lab as string}><Slab position={[x as number,.5,0]} size={[1.5,.8,.12]} color={col as string} fill={.22}/><Tag position={[x as number,1.05,.15]} tone={(i===0?"teal":i===1?"violet":"amber")} size="xs">{lab as string}</Tag>{i<2&&<Ribbon points={[[x as number,.5,0], [(x as number)+.8,.5,0]]} color={col as string} radius={.04} opacity={.8}/>}</group>)}</>}
{mode==="fallback"&&<><Slab position={[-1.8,.5,0]} size={[1.7,1,.14]} color={P.rose} fill={.25}/><Tag position={[-1.8,1.15,.15]} tone="rose">{t.primary}</Tag><Ribbon points={[[-.8,.5,0],[.5,.5,0]]} color={P.violet} radius={.05} opacity={.85}/><Slab position={[1.5,.5,0]} size={[1.7,1,.14]} color={P.violet} fill={.25}/><Tag position={[1.5,1.15,.15]} tone="violet">{t.backup}</Tag><Halo position={[0,.5,0]} radius={.55} color={P.amber} opacity={.55} spin={.2}/><Tag position={[0,-.35,.15]} tone="amber" size="xs">retry → next provider</Tag></>}
{mode==="modes"&&<>{[t.api,t.chat,t.completions].map((lab,i)=><group key={lab}><Slab position={[-2+i*2,.5,0]} size={[1.5,1,.12]} color={[P.teal,P.violet,P.amber][i]} fill={.24}/><Tag position={[-2+i*2,1.15,.15]} tone={(["teal","violet","amber"] as const)[i]} size="xs">{lab}</Tag></group>)}<Node3D position={[0,-.8,0]} color={P.teal} radius={.2} pulse={.3}/><Tag position={[0,-1.3,.15]} tone="muted" size="xs">same intent · different protocol</Tag></>}
</PointerTilt></Stage></Figure> }
